language: r
os:
  - linux
  - osx
cache: packages
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
before_install: |
  cd pkg/micEconIndex
  mkdir ~/.R
  cat <<EOF > ~/.R/Makevars
  CXX1X=g++-4.9
  CXX1XSTD=-std=c++11
# Helpful docs:
# https://docs.travis-ci.com/user/languages/r
#

#
